feat: screen sharing
nextcloud/talk-desktop pull request #595
Opened 2024-04-03 18:03 UTC by ShGKme

### ☑️ Resolves

* Issue #11
* Works in pair with `add link to spreed PR`

### 🖼️ Screenshots

![image](https://github.com/nextcloud/talk-desktop/assets/25978914/37511024-b91c-4e89-9f76-16896564c03d)

### 🚧 Tasks

- [ ] ...

2024-04-05 07:02 UTC, ShGKme commented
Rebased onto main to resolve README conflict

2024-04-05 07:13 UTC, nickvergessen commented
I receive:
```
Error occurred in handler for 'app:getDesktopCapturerSources': TypeError: systemPreferences.getMediaAccessStatus is not a function
    at /home/nickv/Nextcloud/TalkDesktop/talk-desktop/.webpack/main/index.js:48014:24
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:78183)
    at WebContents.emit (node:events:514:28)
```

On linux

2024-04-05 07:44 UTC, nickvergessen commented
Works now, but there is some "stacking issue"

I have to "pick" a screen 3 times. After
1. The "full screen with audio" frame appears
2. The next screen option appears
3. The video in 1. appears

Before 1 | Before 2 | Before 3 | After 3
---|---|---|---
![Bildschirmfoto vom 2024-04-05 09-34-07](https://github.com/nextcloud/talk-desktop/assets/213943/d54294d3-2f26-439b-8f7c-901382284ad0) | ![Bildschirmfoto vom 2024-04-05 09-34-16](https://github.com/nextcloud/talk-desktop/assets/213943/20bddd93-a0d5-4ff5-a5e4-84e7fd9996f4) | ![Bildschirmfoto vom 2024-04-05 09-34-33](https://github.com/nextcloud/talk-desktop/assets/213943/a8d7cc7d-9dd2-48f9-a635-cd6b2ef8f9a4) | ![Bildschirmfoto vom 2024-04-05 09-34-41](https://github.com/nextcloud/talk-desktop/assets/213943/2a4917c4-b770-4392-ad35-7720d545dafc)


:speaking_head: At this moment (After 3) I have a Audio Feedback Loop (is it avoidable to play the shared audio?)

After picking either option I have to accept the screenshare again (but that is also the case with normal Chromium)
![Bildschirmfoto vom 2024-04-05 09-36-02](https://github.com/nextcloud/talk-desktop/assets/213943/bc142635-e1a1-4b31-918d-f25711bd9d0b)

After selecting that the screenshare menu is "open" (should be closed)
![Bildschirmfoto vom 2024-04-05 09-36-17](https://github.com/nextcloud/talk-desktop/assets/213943/6601648b-4915-4d99-8f77-f639b08b91bd)

2024-04-05 09:04 UTC, ShGKme commented
Solution should be different for every OS 🥲

2024-04-05 13:31 UTC, nickvergessen requested changes

2024-04-05 13:31 UTC, nickvergessen commented on src/main.js
> +	if (isMac && systemPreferences.getMediaAccessStatus('screen') !== 'granted') {
```suggestion
	if (isMac() && systemPreferences.getMediaAccessStatus('screen') !== 'granted') {
```

2024-04-08 07:25 UTC, nickvergessen approved these changes

2024-04-08 07:31 UTC, ShGKme commented
> > After selecting that the screenshare menu is "open" (should be closed)
> 
> This is still the case, otherwise fine by me

This part is outside of Talk Desktop...

2024-04-08 07:44 UTC, nickvergessen commented
I never noticed it in the browser. But seems you are right

2024-04-08 09:16 UTC, Antreesy approved these changes
Tested with Linux package, don't have any comments or suggestions. Nice work!

2024-04-08 09:49 UTC, DorraJaouad commented
On Windows, I am not sure it is related to the PR or setup 🙈  :
* Icons are not resized
* Call button is not there and after sharing, the sharing button also disappears

![image](https://github.com/nextcloud/talk-desktop/assets/84044328/65d5f8bb-7191-4f8c-a447-c1528e883a47)


and I think there should be a watcher over streams so when a the modal is open and you close a window, the list gets updated. For now, it turns into a black stream but remains there.

2024-04-08 11:32 UTC, ShGKme commented
> * Icons are not resized

This is `NcDialog` feature... Talk Desktop, and even Talk should have no effect on it. Can you check that you have fresh `npm ci` installed on both `talk-desktop` and `spreed`? And if it is, what styles are applied on the button.

Which version of `spreed` you tested with? 

> * Call button is not there and after sharing, the sharing button also disappears

Also should not be affected by the Talk Desktop...

> and I think there should be a watcher over streams so when a the modal is open and you close a window, the list gets updated. For now, it turns into a black stream but remains there.

Nice catch, checking...

2024-04-08 16:17 UTC, ShGKme commented
> I never noticed it in the browser. But seems you are right

I can reproduce in Web:
1. Start a call
2. Start screen sharing
3. Stop the screen sharing
4. Start screen sharing again
5. The menu is open

I have no idea why it happens

2024-04-08 17:30 UTC, ShGKme commented
> * Icons are not resized

I cannot reproduce, but after some debugging with @DorraJaouad it seems to be Vue 2.7 + weird v-bind CSS issue. It correctly compiles styles, but it doesn't set CSS variable for "v-bind in css" on the root element of `NcIconSvgWrapper`.

2024-04-09 16:37 UTC, ShGKme commented
> and I think there should be a watcher over streams so when a the modal is open and you close a window, the list gets updated. For now, it turns into a black stream but remains there.

Remove preview when the source is not available anymore and request sources each second to check for new sources.

cc @DorraJaouad

2024-04-09 20:23 UTC, ShGKme commented
> All good 💯

Even icons? o_O

2024-04-09 20:40 UTC, DorraJaouad commented
> Even icons? o_O

No :( , but it's not related to this PR.

2024-04-10 10:35 UTC, merged