Basic tray icon implementation
nextcloud/talk-desktop pull request #79
Opened 2023-03-24 14:33 UTC by p-try

### ☑️ Resolves

#28 Stay in tray

### 🖼️ Screenshots

🏚️ Before | 🏡 After
---|---
./. | ![grafik](https://user-images.githubusercontent.com/7594671/227553518-4864c79f-cf36-4428-aa1c-dc34f0841340.png)

### 🚧 Tasks

- [X] Add tray icon
- [X] Main window minimizes to tray
- [ ] Clicking on notifications opens main window

2023-03-24 14:52 UTC, nickvergessen commented
Nice stuff 🤩

2023-03-24 15:18 UTC, nickvergessen commented
Hi @p-try ! :) We have a Nextcloud Talk instance where we invite Nextcloud contributors to be able to communicate more quickly, and we also have channels for e.g. "Talk app team". If you like, I could give you a guest account via the email address from your copyright (or any other email)?

2023-03-24 15:24 UTC, p-try commented
Thank you very much, I'd like that!

2023-03-29 12:23 UTC, marcoambrosini reviewed
I'm testing this on Mac OS 13.2.1 and no tray icon is visible

2023-03-29 19:43 UTC, p-try commented
> I'm testing this on Mac OS 13.2.1 and no tray icon is visible

There seem to be some special requirements for MacOS that I have not considered. I will implement them and get back to you for a test.

2023-03-29 19:55 UTC, nickvergessen commented
@ShGKme you also wanted to leave a comment here, right?

2023-03-30 20:03 UTC, ShGKme requested changes
Hello @p-try,

Thank you for you contribution!

It works. I think, we may make the tray implementation less "basic" and then merge it.

Also, we use [ESLint](https://eslint.org) for checking formatting and code-style. Please, run `npm run lint` and fix linting errors.

2023-05-23 08:55 UTC, p-try commented
> Hello @p-try,
> 
> Thank you for you contribution!
> 
> It works. I think, we may make the tray implementation less "basic" and then merge it.
> 
> Also, we use [ESLint](https://eslint.org) for checking formatting and code-style. Please, run `npm run lint` and fix linting errors.

Agreed. Sorry I wasn't able to follow up to this so far but I should find time shortly to work on this.

2023-06-20 20:03 UTC, p-try commented on src/app/app.tray.js
> +	const tray = new Tray(path.join(__dirname, '..', '..', 'img', 'icons', 'icon.png'))
Currently, the icon will only work in development as the icon files are not yet copied to the build directory. I suggest CopyWebpackPlugin for this but I think this should be addressed in a separate discussion as this is about asset files in general and there may be more in future.

2023-06-28 15:58 UTC, ShGKme reviewed
Hi @p-try 

Thanks for your updates!

Could you rebase onto `main` and fix conflicts? And then we can merge it.

You would probably need to move the `mainWindow` setup to the end of the talk window creation on `appData:receive` (after line 157 in the current `main`).

https://github.com/nextcloud/talk-desktop/blob/32aa45a6e2317add5f9781a56360496eff28ee0a/src/main.js#L148-L157

App initialization is a bit changed now to handle and re-fetch invalid application data.

2023-06-30 21:31 UTC, p-try commented
Thank you so much for your great guidance, @ShGKme!

I have found that I had to add the minimize-to-tray setup both in the `appData:receive handler` and the `authentication:login` handler because the talk window is initialized in both. Otherwise the tray icon would not work right after logging in but only on a fresh app instance when the authentication was skipped. I am not sure if my proposed solution for this is the best way as it appears a bit fiddly to me.

https://github.com/p-try/talk-desktop/blob/f0d464b1d31f7f424cd5f05ac77528b2de7350fb/src/app/app.tray.js#L60-L67

2023-07-04 15:01 UTC, ShGKme commented
Hi @p-try,

> I have found that I had to add the minimize-to-tray setup both in the appData:receive handler and the authentication:login handler because the talk window is initialized in both. 

Yes, it makes sense, cool!

> I am not sure if my proposed solution for this is the best way as it appears a bit fiddly to me.

https://github.com/p-try/talk-desktop/blob/f0d464b1d31f7f424cd5f05ac77528b2de7350fb/src/app/app.tray.js#L60-L67

It's fine. We need to improve window management anyway, but after some point when it will be clear, what we want to do with all the windows, initializations, setups and etc.

---

Could you make a `rebase onto main`, not merge? Otherwise, this PR has all the commits now from Marth and all the changes in Files changes.

We use rebase to keep PR up to date on `master`/`main` in all our repositories.

Feel free to DM me in Talk with your guest account if you need any help.

2023-07-04 19:44 UTC, p-try commented
Looks like this was a GitHub hiccup as I had rebased on main but it had still shown all the previous commits from when I had merged two weeks ago. Editing the PR to change the base branch to something else and then changing it back to main seems to have fixed the commit list.

2023-07-05 16:20 UTC, ShGKme commented
@p-try would you mind if I rebase your branch and force push?

2023-07-06 21:30 UTC, ShGKme commented
Hi @p-try 

I have updated your fork:
1. Drop the last commit with merge `origin/tray_icon` to `tray_icon`
2. Rebase onto the current main
3. `push --force-with-lease`

If you don't have any new local changes, you need to `fetch` and `reset origin/tray_icon` (not `pull`). If you have any new local changes, stash or cherry-pick commit.

The last problem DCO and commit author mismatch in https://github.com/nextcloud/talk-desktop/pull/79/commits/74ad3b8493971f29aea5aafb645c430e69f67333.

You need to update this commit description with interactive rebase and then do `git push --force-with-lease` again.

2023-07-10 10:19 UTC, p-try commented
Thank you so much for your detailed instructions!

2023-07-17 22:27 UTC, ShGKme approved these changes
Thanks for your contribution, I think, we can merge it now :)

2023-07-17 22:28 UTC, merged